### PR TITLE
Fix(babel): Make babel polyfill Object.assign

### LINKED ISSUE #85: babel-preset-es2015 does not polyfill Object.assign
IE11

Object.assign error cause

why?

### PR DESCRIPTION
**Pull request by BerkeleyTrue**
closes #85 

@pouu69 Would you have some time to test if this solves your issue?

ping @pburtchaell

### CODE REVIEW

**Comment by pburtchaell** [comment]
This change looks good to me. I'll wait for @pouu69 to let us know if it solves the issue.

**Comment by pburtchaell** [comment]
Let's just merge this in and release, @BerkeleyTrue.

**Comment by BerkeleyTrue** [comment]
@pburtchaell Ok cool. You want to hit that merge button? I'm not keen on merging in my own PR's.

**Comment by pburtchaell** [comment]
This is released as `react-notification@6.1.1`.

**Pull request merged**
