### PR TITLE
Bugfix: use ... replace Object.assign()

### PR DESCRIPTION
**Pull request by huybery**
the [Issues #85](https://github.com/pburtchaell/react-notification/issues/85) because the lower brower can't  support object.assign

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Replacing Object assign with the spread polyfill doesn't actually remove the Object.assign call. Babel transpiles the spread operator to a Object.assign.

Also, If a browser doesn't support Object.assign, it is very unlikely that it will support the spread operator.

Lastly, this PR wouldn't fix #85 as that issue's cause is yet to be determined. As stated in the issue, babel will polyfill object.assign if it is not supported by the browser.

**Comment by huybery** [comment]
sorry English is not my native language ，please excuse typing errors. 
> Replacing Object assign with the spread polyfill doesn't actually remove the Object.assign call. Babel transpiles the spread operator to a Object.assign.

why I use spread polyfill,the bable will translate that:
```
return isActive ? _extends({}, baseStyle, {
        left: '1rem'
      }, barStyle, activeBarStyle) : _extends({}, baseStyle, barStyle);

```
_extends :

```
var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };
```

but Object.assign can't translate that.

when i use react-notification on the Android built-in browser， use Object.assign will have a bug, but use spread polyfill will good. so I pull requests this.

Lastly， Thank you for your open source :smile:

**Comment by BerkeleyTrue** [comment]
@pburtchaell Looks like babel-plugin-es2015 might no longer polyfil Object.assign:

[https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=true&presets=es2015%2Creact%2Cstage-0%2Cstage-2&code=var%20foo%20%3D%20%7B%7D%3B%0Avar%20bar%20%3D%20Object.assign(%7B%7D%2C%20foo%2C%20%7B%20bar%3A%20'bar'%20%7D)%3B%0Avar%20baz%20%3D%20%7B%20...foo%2C%20baz%3A%20'baz'%20%7D%3B](babel/repl)

**Comment by BerkeleyTrue** [comment]
@pburtchaell We might need to add https://babeljs.io/docs/plugins/transform-object-assign/ 

I've hit up the twitterverse to figure out why preset-es2015 does not include this transform.

**Comment by pburtchaell** [comment]
@BerkeleyTrue cool. Thanks for owning this. 😄 I'm going to reopen #85.

**Comment by BerkeleyTrue** [comment]
@pburtchaell Mind making me a contributor? FCC is depending on this project so I would like to contribute to maintaining it.

**Comment by pburtchaell** [comment]
Sure, what is your npm username?

**Comment by BerkeleyTrue** [comment]
Same as github. BerkeleyTrue

**Comment by pburtchaell** [comment]
Awesome! I've added you to GitHub and npm. My only two requests: update release notes and copy me on PRs before merging feature branches. Thanks for asking to be added. I appreciate the help. 😄

**Pull request closed without merging**
