### PR TITLE
Add support for React version 0.14.0

### PR DESCRIPTION
**Pull request by pburtchaell**
- [ ] Update examples 
- [ ] Make sure tests pass
- [x] Update peerDependencies
- [x] Update dependencies 
- [x] Update devDependencies 
- [x] Rebase to master to get GPU acceleration

### CODE REVIEW

**Comment by trueter** [comment]
Any updates on this?

**Comment by pburtchaell** [comment]
I have been swamped with work lately. I will be unavailable to work on it this weekend, but hope to get to it within the next week.

**Comment by MathieuDoyon** [comment]
+1

**Comment by pburtchaell** [comment]
This has been released as `react-notification@3.0.1`. Let me know if you have any issues. :smile:

**Pull request merged**
