### PR TITLE
Allow `action` and `onClick` for Stacked Notifications

### LINKED ISSUE #46: Actions Link on NotificationStack
I would like to add an `x` or `close` link on `NotificationStack`.
Currently, `NotificationStack` will just fade away after several secs that is set.
How can I stack multiple `Notification` with `action` and `onClick` props?

### PR DESCRIPTION
**Pull request by elrumordelaluz**
Resolves #46.

Add references to timeouts that allows to clear them before unmount each notification. 
So, let available to add `action` and `onClick` props in `Notification`s Components inside a Stack. #46 

I tryied to let the example as it is (using `OrderedSet`from Immutable.js) but didn't find a way to reference each generated `Notification` Component inside its own `onClick` prop, so I changed the example with a raw Object, referenced with an _unique_ id  based on `Date.now()` (with the same advice comment).

stacnotif

### CODE REVIEW

**Comment by pburtchaell** [comment]
@elrumordelaluz I'm busy over the next few days, but I'll take a look at this on Friday evening.

**Comment by pburtchaell** [comment]
@elrumordelaluz This looks good. Can you rebase so the older commits aren't on the branch? Once you do that I will merge and release!

**Comment by pburtchaell** [comment]
Note, this resolves #46.

**Comment by elrumordelaluz** [comment]
> Can you rebase so the older commits aren't on the branch? 

I realised that there are duplicated commits in the PR, I'm sorry.

Due to my [lack of deep knowledge](http://stackoverflow.com/questions/36495012/how-to-rebase-to-avoid-duplicated-commits-on-pull-request) in Git area I'm trying different ways to solve it asap, then will send to you.

**Comment by cliftonc** [comment]
@elrumordelaluz need any further assistance?  This is a really useful PR for me, so happy to help if I can.

**Comment by elrumordelaluz** [comment]
@cliftonc oh sure, I thought there were a pretty simple `git` thing to solve, but then I found my fork in a little mess. Probably is a simple thing to solve, if you have 5 mins I'll appreciate your support.

**Comment by elrumordelaluz** [comment]
Closed because of state problems on my fork.

**Pull request closed without merging**
