### PR TITLE
Add initial TypeScript definitions

### PR DESCRIPTION
**Pull request by corydeppen**

### CODE REVIEW

**Comment by pburtchaell** [comment]
I can't provide an actual review because I don't have experience with TS, but this looks fine to me. 🤔 

Copying both @BerkeleyTrue and @joeyfigaro here as well. If either of y'all have experience with TypeScript, would you mind taking a look at this? 💯  

It does seem the build is failing, but based off [the logs](https://travis-ci.org/pburtchaell/react-notification/builds/241856731?utm_source=github_status&utm_medium=notification) I don't think that's caused by your diff, @corydeppen. I'll take a closer look.

**Comment by BerkeleyTrue** [comment]
@pburtchaell  jsdom 11 now requires node 6 and travis is still configured to run node 4

**Comment by BerkeleyTrue** [comment]
@corydeppen Can you also add tests for these typings?

**Comment by pburtchaell** [comment]
@BerkeleyTrue what are you think is the best way to approach testing this?

@corydeppen can you rebase your branch against master? That will fix the build errors.

**Comment by BerkeleyTrue** [comment]
An example:

https://github.com/redux-observable/redux-observable/blob/master/test/typings.ts
https://github.com/redux-observable/redux-observable/blob/master/package.json#L18

This file is first run through the typescript compiler to ensure there are no issues with the typings, then the compiled file is run. This ensures the typings are always tested against the latest codebase.

**Comment by corydeppen** [comment]
When I started looking into how other projects tested their definitions, I landed on the Redux repo ([example](https://github.com/reactjs/redux/blob/master/test/typescript.spec.js)). Using the [typescript-definition-tester](https://www.npmjs.com/package/typescript-definition-tester) package, it looks like it should integrate nicely into the existing test setup. Aside from the integration and using the definitions in this repo, I thought this might also allow for a new `typescript` directory to be added to the existing `examples` directory to both show the usage as well as provide source to test compilation.

Thoughts?

**Comment by pburtchaell** [comment]
Hey @corydeppen, sorry for the delay here, but I missed the email for your comment and just saw it. That sounds good to me.

**Comment by pburtchaell** [comment]
@corydeppen What is the status of this PR?

**Comment by corydeppen** [comment]
I hope to get back and finish up the tests this week.

**Comment by corydeppen** [comment]
@pburtchaell I have a test compiling an example directory containing components that reference the project's TypeScript declaration file. Since the components are just TS versions of the existing JS examples, do you want to include these components in the running examples or is it sufficient to just ensure the examples compile using the TS definitions? It won't be much extra work to get them running (include the loader and modify the Webpack config and HTML files), but I wanted to check before making the changes.

**Comment by pburtchaell** [comment]
@corydeppen Can you include them in the [test directory](https://github.com/pburtchaell/react-notification/tree/master/test) so it's clear for others that they are test files?

**Comment by corydeppen** [comment]
@pburtchaell The new test should adequately exercise the TS declaration file using new components based on the ones in the examples directory. Please review.

**Comment by pburtchaell** [comment]
Great! This is merged and released as `react-notification@6.8.2` on npm.

**Pull request merged**
