### PR TITLE
Add actionStyleFactory prop to NotificationStack component

### PR DESCRIPTION
**Pull request by joeellis**
Hey @pburtchaell, long time no see!

Found this library when looking up react notification libs out there and thought it was really cool.  Created this PR because I'm looking to do different stylings depending on the 'level' of the notification (`success`, `error`, etc).

AFAICT the `NotificationStack` component allows us to override the main bar styles, but it didn't seem to give us access to override the styles for the action part.  So this PR attempts to add that in.  

Just let me know if you have some other future direction for this kind of stuff or if there is anything I can fix up.  thanks!

### CODE REVIEW

**Comment by pburtchaell** [comment]
Hey @joeellis! 👋 

This looks good to me. I'll merge in and release later this week.

**Comment by joeellis** [comment]
@pburtchaell Awesome, thanks!

**Comment by joeellis** [comment]
Hey @pburtchaell, any chance this could get merged this week?

**Comment by pburtchaell** [comment]
Yep, sorry for the delay! This is released as `react-notification@6.8.0`.

**Pull request merged**
