### PR TITLE
Added title option

### PR DESCRIPTION
**Pull request by Lacerda**
Added title option to the notification.
Started using this project and really missed the option to add a title to the notification.

### CODE REVIEW

**Comment by pburtchaell** [comment]
Hi @Lacerda, thanks for the PR! Two things:

1. Please ensure tests pass.
2. Can you post a screenshot of the UI change?

**Comment by Lacerda** [comment]
Hey! :)
The test are passing, Travis is complaining about unmet peerDependencies. There is a problem with the version of `eslint`.

```
npm ERR! peerinvalid The package eslint@2.6.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-config-airbnb@6.2.0 wants eslint@^2.4.0
npm ERR! peerinvalid Peer babel-eslint@5.0.4 wants eslint@<2.3.0
```

Here is the screenshot: https://cloudup.com/cEzwilT30la
:)

**Comment by pburtchaell** [comment]
Ok great, I opened an issue for ESLint: #60. The screenshot looks good. :+1: 

One last thing and this will be ready for merge: can you change the PR so the component doesn't include the title by default, e.g., you have to provide a title prop for it to show?

**Comment by Lacerda** [comment]
Unless I misunderstood something that's the way it is implemented. :) The title will only appear if you provide a title.

**Comment by pburtchaell** [comment]
Ah ok! I just realized I misread your code changes. I'll merge and release this shortly.

**Comment by Lacerda** [comment]
Cool! Thank you!

**Comment by pburtchaell** [comment]
This is released as version `react-notification@5.0.1`. :smile:

**Pull request merged**
