### PR TITLE
Fix styles

### PR DESCRIPTION
**Pull request by pburtchaell**
This PR resolves issues #47 and #48. It also adds a number of new unit tests for both components, focusing on CSS/style testing.

### CODE REVIEW

**Comment by dinosaurcop** [comment]
Would like to put react-notifications into our production app, will this be merged soon?

**Comment by brianespinosa** [comment]
I'm watching this PR as well hoping for a version bump in NPM once merged.

**Comment by pburtchaell** [comment]
@brianespinosa @dinosaurcop I made progress today. I need to add tests and documentation for the changes and then I'll release.

**Comment by brianespinosa** [comment]
@pburtchaell Great, thanks for the update. :+1:

**Pull request merged**
