### PR TITLE
Dynamically control bar bottom value

### LINKED ISSUE #57: Override value of "bottom" CSS attribute
I looked through the code for this component and it appears that the `bottom` CSS attribute is hard coded in this component with the logic for placement passed on to each notifications. Are you opposed to a solution that would allow the `barStyle` property to also set `bottom` in a dynamic way?

### LINKED ISSUE #77: Remove all inline styles
Hi.

I want to use [these classes ](http://v4-alpha.getbootstrap.com/components/alerts/), but when I add them nothing is changing.

If I set `style` to false, the animation is no longer working

### PR DESCRIPTION
**Pull request by BerkeleyTrue**
Adds the ability to pass in a function for either `barStyle` or `activeBarStyle` props on the NotificationStack component. This makes the bottom css value controllable by the user.

Resolves #57.
Resolves #77.

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Hey @pburtchaell,

I needed this so I went ahead and started a PR.

Let me know if anything needs to be changed.

A couple of notes: The naming could be better. Maybe instead of barStyle and activeBarStyle the properties could be named barStyleFactory and activeBarStyleFactory. Explicit is better than implicit, I always say.

**Comment by pburtchaell** [comment]
Thanks for this PR! I've been waiting for someone to implement this. 😄

> Adds the ability to pass in a function for either barStyle or activeBarStyle props on the NotificationStack component.

Can one still pass an object to the props? 

> The naming could be better. Maybe instead of barStyle and activeBarStyle the properties could be named barStyleFactory and activeBarStyleFactory. Explicit is better than implicit, I always say.

Yeah, the best solution might be to use `barStyle` and `activeBarStyle` properties for a style object and `barStyleFactory` and `activeBarStyleFactory` for the custom position. What do you think?

**Comment by pburtchaell** [comment]
Also, this PR should resolve #77 as well!

**Comment by BerkeleyTrue** [comment]
> Can one still pass an object to the props?

This wasn't possible before as the props don't pass through from NotificationStack to StackedNotification. They do pass from the notifications objects to the StackedNotification, so this PR does not change that behavior.

> Yeah, the best solution might be to use barStyle and activeBarStyle properties for a style object and barStyleFactory and activeBarStyleFactory for the custom position. The factory properties would override the object properties. What do you think?

I can change the name of the functions but adding the ability to pass in global barStyle/activeBarStyle should come as a separate PR as it would be a new feature.

>  Also, this PR should resolve #77 as well!

Yes it is possible, but it also possible but it would involve add a null value for all the style props unrelated to position. I think that PR would be better served by separating the built in style properties related to look and position, and add a new prop to NotificationStack and Notification to deactivate them separately.

I'll make the changes to the names of those functions and update this PR.

**Comment by BerkeleyTrue** [comment]
@pburtchaell I've made those changes.

**Comment by BerkeleyTrue** [comment]
ping @pburtchaell

**Comment by pburtchaell** [comment]
Thanks for your work here. This is related as `react-notification@6.0.0`. 😄

**Pull request merged**
