### PR TITLE
Implement notification stack

### PR DESCRIPTION
**Pull request by pburtchaell**
This PR:
- Updates initial notification list code from PR #40 (component renamed to `<NotificationStack/>`)
- Fixes WebPack 
- Adds separate examples for a notification stack v. a single notification

### CODE REVIEW

**Comment by pburtchaell** [comment]
@meta-meta I merged in your code and made some changes to it. I should be able to work on this more over the next few days and then get it merged in. Thanks for getting this started!

**Comment by meta-meta** [comment]
Looking good. Glad I could be of service!

**Comment by unkw** [comment]
When will merge?

**Comment by pburtchaell** [comment]
I am busy this week with finals and wrapping up the fall semester. I'll be back working on this next week.

**Comment by unkw** [comment]
Thanks! I'll wait

**Pull request merged**
