### PR TITLE
fix constructor for slow browsers

### PR DESCRIPTION
**Pull request by leshek-pawlak**
Hi!
I use react-notification in my current project.
I think - it's a great job!

But I realized that it's not working for IE9. 

This small change in the code fixes setting the dismissTimeout for slow browsers.

Greetings!

### CODE REVIEW

**Comment by pburtchaell** [comment]
Thanks for the PR! 

Before I merge — I don't work a lot with IE9. Could you explain why removing `this` increases performance for older browsers?

**Comment by leshek-pawlak** [comment]
It's not about performance, but about working. 😄 

I just did "console.log" in the IE9 constructor. 
"this.props" is undefined, but "props" looks perfect. 

I think it's because the constructor function is started immediately after the create class function. 
In slow browsers, the time between create the class object and start the constructor is too short to properly create the entire object.
And probably that's why we have to pass "props" as an argument in the constructor and super functions. 😉 

I tried to find an article about this on the net, but I couldn't find anything. 😉

**Comment by pburtchaell** [comment]
Got it! I misunderstood your description of the PR. 😓 

I will review again this weekend and then merge and release a new version if everything looks okay. Thanks!

**Comment by pburtchaell** [comment]
This is released as `react-notification@6.1.0`.

**Pull request merged**
