### PR TITLE
Fix DismissAfter hardcoded in notification stack.

### PR DESCRIPTION
**Pull request by sergiofm**
Hi! I've fixed this issue: https://github.com/pburtchaell/react-notification/issues/43

### CODE REVIEW

**Comment by pburtchaell** [comment]
Thanks for this! I'm going to try review the code changes tomorrow; if everything looks good, I'll merge and release. :smile:

**Comment by sergiofm** [comment]
I have another fix send to you. If you can wait a little to release, I'll send it right after you accept the first pull request, so you can release the two fixes together.

**Comment by pburtchaell** [comment]
This looks good. I've released it as `react-notification@4.2.0`. 

Regarding your second fix, I'll just make another release for it.

**Comment by sergiofm** [comment]
Oh, the second fix was already in my first pull request and I didn't noticed.

**Pull request merged**
