### PR TITLE
Add onClick prop to NotificationStack definition

### PR DESCRIPTION
**Pull request by sh3nan1gans**
Hello! :wave: 

This template enables you to open an issue that is valuable for you, the project, and the GitHub community. :two_hearts:

Before submitting an issue, please:
1. Agree the [Code of Conduct](/.github/CODE_OF_CONDUCT.md).
2. Read the [Contributing Guide](/.github/CONTRIBUTING.md).

If you are new to open source, check out this 38 minute course on [how to contribute to open source on GitHub](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github). It's free! :smile:

---

Before submitting a pull request, please make sure the following is done:

1. Add tests for new functionality or bug fixes, following the [red/green/refactor method](https://en.wikipedia.org/wiki/Test-driven_development#Development_style)
2. Ensure all tests pass: `npm test`
3. Update and/or add documentation

**In order to merge your Pull Request, tests and documentation are required.**

### CODE REVIEW

**Comment by pburtchaell** [comment]
This is released as `react-notification@6.8.3`. Thanks!

**Comment by sh3nan1gans** [comment]
Thanks @pburtchaell ! Any chance that you can publish the new version to npm?

**Comment by pburtchaell** [comment]
Sure, sorry for the delay. I thought it was published... let me check!

**Comment by pburtchaell** [comment]
Okay @sh3nan1gans, it should be released now. I'm sorry for the confusion there. Enjoy!

**Comment by sh3nan1gans** [comment]
@pburtchaell - I'm having issues with installing the latest release. Looks like an issue with the generate-lockfile script. Here's a repro repo - https://github.com/sh3nan1gans/test-install-react-notification

**Comment by pburtchaell** [comment]
Okay, thanks. I'll take a look.

**Comment by pburtchaell** [comment]
The changes in PR #145 should fix this because I removed the generate-lockfile script in that PR.

**Comment by pburtchaell** [comment]
Would you mind installing that branch (PR #145), @sh3nan1gans, and letting me know if you get the error? The branch is rebased from master and includes the commits from this PR.

**Comment by pburtchaell** [comment]
You can install it with:

```
npm install git://github.com/pburtchaell/react-notification.git#pburtchaell-parcel
```

**Comment by sh3nan1gans** [comment]
@pburtchaell - That branch worked perfectly 👍

**Comment by pburtchaell** [comment]
Great! I will get that merged and published. 😄

**Comment by pburtchaell** [comment]
`react-notification@6.8.3` is now deprecated due to that installation error. The latest release is `react-notification@6.8.4`, which includes the changes from this PR #149 and from PR #145. Enjoy!

**Comment by pburtchaell** [comment]
Also, thanks for your contribution and your help debugging! 💯

**Comment by sh3nan1gans** [comment]
Awesome. Thank you! And thanks for this great library

**Pull request merged**
